language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install: pip install --upgrade pip setuptools tox-travis coveralls
script: tox
after_success: coveralls

deploy:
  provider: pypi
  user: ${PYPI_USERNAME}
  password: ${PYPI_PASSWORD}
  distributions: sdist bdist_wheel
  on:
    tags: true
